# Generated by Django 2.2.1 on 2019-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Censo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
                ('estatus', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Existencia_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_censo', models.IntegerField()),
                ('folio_producto', models.IntegerField()),
                ('cantidad_fisica', models.FloatField()),
                ('cantidad_teorica', models.FloatField()),
                ('diferencia', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('unidad_medida', models.FloatField()),
                ('estatus', models.CharField(max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
                ('estatus', models.CharField(max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.IntegerField()),
                ('id_producto', models.IntegerField()),
                ('cantidad', models.FloatField()),
            ],
        ),
    ]
