# Generated by Django 2.2.1 on 2019-05-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_producto',
            name='unidad_medida',
            field=models.CharField(max_length=2),
        ),
    ]
