# Generated by Django 2.2.1 on 2019-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190522_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario_producto',
            name='estatus',
            field=models.CharField(default='V', max_length=1),
        ),
    ]
