# Generated by Django 2.2.1 on 2019-05-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20190522_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Censo_producto',
            new_name='Censo',
        ),
        migrations.RenameModel(
            old_name='Existencia_producto',
            new_name='Existencia_censo',
        ),
        migrations.DeleteModel(
            name='Pedido_producto',
        ),
        migrations.DeleteModel(
            name='Producto_pedido',
        ),
    ]
