# Generated by Django 2.2.1 on 2019-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('folio_clase', models.IntegerField()),
                ('estatus', models.CharField(max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clase_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Costo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_producto', models.IntegerField()),
                ('costo', models.FloatField()),
                ('venta', models.FloatField()),
                ('iva', models.FloatField()),
                ('margen', models.FloatField()),
                ('estatus', models.CharField(max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Familia_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.CharField(max_length=100)),
                ('folio_categoria', models.IntegerField()),
                ('estatus', models.CharField(max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('folio_familia', models.IntegerField()),
                ('estatus', models.CharField(default='V', max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
            ],
        ),
    ]
