# Generated by Django 2.2.1 on 2019-05-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='foto',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
