# Generated by Django 2.2.1 on 2019-05-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_auto_20190517_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigo_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField()),
                ('Codigo', models.CharField(max_length=20)),
            ],
        ),
    ]
