# Generated by Django 2.2.1 on 2019-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('foto', models.CharField(max_length=150000)),
                ('estatus', models.CharField(default='V', max_length=1)),
                ('usuario_creo', models.IntegerField(default=0)),
                ('usuario_modifico', models.IntegerField(default=0)),
            ],
        ),
    ]
