# Generated by Django 2.2.1 on 2019-05-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Telefono',
            field=models.CharField(max_length=20),
        ),
    ]
