# Generated by Django 2.2 on 2019-07-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_productos_orden_folio_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_modificacion',
            field=models.DateField(),
        ),
    ]
