# Generated by Django 2.2 on 2019-06-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_asignacion_caja_producto_ticket_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion_caja_corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_asignacion', models.IntegerField()),
                ('efectivo', models.FloatField()),
                ('cheques', models.FloatField()),
                ('vouchers', models.FloatField()),
                ('total', models.FloatField()),
                ('total_corte', models.FloatField()),
                ('diferencia', models.FloatField()),
                ('usuario_creo', models.IntegerField()),
                ('usuario_modifico', models.IntegerField()),
                ('estatus', models.CharField(max_length=1)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='asignacion_caja',
            old_name='cheques',
            new_name='fondo_caja',
        ),
        migrations.RenameField(
            model_name='asignacion_caja',
            old_name='folio_asignacion',
            new_name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='asignacion_caja',
            name='diferencia',
        ),
        migrations.RemoveField(
            model_name='asignacion_caja',
            name='efectivo',
        ),
        migrations.RemoveField(
            model_name='asignacion_caja',
            name='total',
        ),
        migrations.RemoveField(
            model_name='asignacion_caja',
            name='total_corte',
        ),
        migrations.RemoveField(
            model_name='asignacion_caja',
            name='vouchers',
        ),
    ]
