# Generated by Django 2.2.1 on 2019-06-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20190608_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='disenioTicket',
            field=models.CharField(default='<h1>Sin Datos</h1>', max_length=20000),
        ),
    ]
