# Generated by Django 2.2 on 2019-06-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_ticket_disenioticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion_caja_corte',
            old_name='cheques',
            new_name='retiros',
        ),
    ]
